/* Generated from the original NOGTEXT.H; do not edit. */
/* Source SHA-256: 9c69c5785355841b8a2135b2f169a6b03b7d37edee7ed896cd393fedfcd79f35 */

#include "nk_dialogue.h"

#include "stddef.h"

const NkDialogueEntry nk_dialogue_entries[] =
{
  { 0, 1100U, NULL },
  { 1, 400U, "Wow! Moving paddle action." },
  { 0, 200U, NULL },
  { 2, 300U, "Indeed. I could play this all day." },
  { 3, 0U, "Well, you two better get used to it!" },
  { 3, 0U,
    "I'm going to keep you strapped here in total agony until you reveal to me the secret "
    "location of Bloodlust Software World Headquarters!!" },
  { 0, 200U, NULL },
  { 1, 0U, "Blow it out of your undersized ass, Stumpy." },
  { 3, 0U, "Ahh..So I see that the heightling wants to play!" },
  { 3, 0U, "We shall play, oh yes, we shall play..." },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 3, 0U, "I shall keep you two infidels trapped in the room of eternal pong forever!" },
  { 2, 0U, "Someone needs to tell that midget to shut up...." },
  { 2, 0U, "..or else I'll pound him into half a midget." },
  { 1, 0U, "....isn't that like an eighth of a real man\?" },
  { 2, 0U, "..or a sixteenth of Andre the Giant." },
  { 0, 200U, NULL },
  { 1, 0U, "Midgets serve only one purpose, and that's chucking." },
  { 2, 0U, "The only good midget is a chucked midget, I always say." },
  { 0, 200U, NULL },
  { -1, 0U, NULL },
  { 1, 400U, "Hey, do you know what the term 'squat launching' means exactly\?" },
  { 0, 200U, NULL },
  { 2, 0U, "Are you a retard or something\?" },
  { 2, 0U, "You DON'T know what the term 'squat launching' means\?" },
  { 1, 0U, "Wait a second, buddy..." },
  { 1, 0U,
    "Are you trying to tell me that everyone who's not a retard knows what a 'squat "
    "launch' is\?" },
  { 2, 0U, "Precisely." },
  { 1, 0U,
    "Look here, if everyone who didn't know what 'squat launching' means is a tard, then "
    "there wouldn't be enough tardwagons in existence to take everyone bowling." },
  { 1, 0U, "It's just mathematically impossible." },
  { 1, 0U,
    "Hmmm, maybe you could transport the tards using a long bus, instead of the short ones." },
  { 1, 0U, "You could transport twice the tards in half the time." },
  { 2, 0U, "Are YOU INSANE or something\?\?" },
  { 2, 0U,
    "You can't use the long bus to transport tards! Its a violation of all the tardwagon "
    "driver ethics that I abide by!" },
  { 2, 0U, "You'll disrupt the whole space-tard continuum!" },
  { 1, 0U, "Oh, dear me! What was I thinking!\?" },
  { 0, 200U, NULL },
  { -1, 0U, NULL },
  { 1, 400U, "Hey, I don't think you like tards as much as I do." },
  { 2, 0U,
    "Listen, as a tardwagon driver myself, I happen to know tards like no one else knows "
    "tards." },
  { 2, 0U, "And let me tell you something, buddy..." },
  { 2, 0U, "If you don't have your tard card, you aint getting on the tardwagon." },
  { 1, 0U, "What if I had a letter from my mom\?" },
  { 2, 0U, "Nope, sorry buddy." },
  { 1, 0U, "What if I provided you with drool samples\?" },
  { 2, 0U, "Nope, no can do, buddy." },
  { 1, 0U, "What if I wore a black cardboard box and did some Downy performance art\?" },
  { 0, 200U, NULL },
  { 2, 0U, "If you don't have your tard card, you aint getting on the tardwagon." },
  { 2, 0U, "It's the rules of the road, buddy." },
  { 0, 200U, NULL },
  { -1, 0U, NULL },
  { 1, 600U, "..Shweee bop. Shweee bop bop da ta da..." },
  { 2, 0U, "..shwee bop da ta da..bop da ta da ta..." },
  { 0, 400U, NULL },
  { 1, 0U, "Nothing like some tirebiter tunes to get your toes a' tapping." },
  { 0, 800U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "I'm starting to like this electricity, it's making my nipples perk up." },
  { 1, 0U, "Yep." },
  { 1, 0U, "Perks them up quicker than a pencil flicking." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "Damn. I'll be right back. I gotta go take a pee pee." },
  { 1, 0U, "Don't go scoop diving..." },
  { 2, 0U, "Damn! ARGGH...Stumpy really bolted us down good!" },
  { 2, 0U, "*grunt* I can't get out of my electric chair! *grunt*" },
  { 1, 0U, "Looks like the floor will have a new yellow shine pretty soon..." },
  { 2, 0U,
    "Stumpy!! You bastard! How do you expect us to go tinkle when we are strapped down "
    "like this\?" },
  { 3, 0U,
    "You pathetic tall man! Even if I were to free you, there's no way you could use the "
    "restroom here." },
  { 3, 0U,
    "All of the urinals have been lowered to midget-heights, and are unusable by "
    "heightlings such as yourself!" },
  { 2, 0U, "DAMN YOU!! How clever of you to lower those urinals..." },
  { 2, 0U, "I am defeated." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Hey, Stumpy...what's that unusual bulge in the front of your tights\?" },
  { 2, 0U, "EWWW...what kind of question is that\?" },
  { 1, 0U, "It's just a question." },
  { 2, 0U, "You midget-crotch-looker!" },
  { 1, 0U, "I wasn't looking at his crotch!" },
  { 1, 0U, "It's very rare that I'm eye-level with a midget's crotch." },
  { 2, 0U, "Midget-crotch-looker!" },
  { 3, 0U, "Enough bickering about my package!" },
  { 1, 0U, "It seems like Stumpy had some limb-lengthening surgery..." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "Okay, real quick....underwear check!!" },
  { 1, 0U, "I'm wearing boxers." },
  { 2, 0U, "I'm wearing boxers here too...." },
  { 0, 100U, NULL },
  { 3, 0U, "I'm wearing...ummm...errrr...." },
  { 1, 0U, "Cough it up Stumpo! It's an underwear check..." },
  { 3, 0U, "...wait a second! This is some midget joke isn't it\?" },
  { 2, 0U, "No it's not." },
  { 2, 0U, "It's just an underwear check." },
  { 3, 0U, "You want me to say that I wear briefs, don't you\?!" },
  { 3, 0U, "Briefs! I wear briefs! Are you guys happy now\?\?!" },
  { 1, 0U, "Hehehe." },
  { 2, 0U, "Hehehe." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "Hey, Stumpy, do you have any cavities\?" },
  { 3, 0U, "No." },
  { 0, 300U, NULL },
  { 2, 200U, "Heheheh..." },
  { 1, 0U, "Hehehehe!" },
  { 2, 200U, "Hahahaahaa..." },
  { 1, 200U, "Tee hee tee hee!!" },
  { 2, 200U, "Ho ho ho ho ho ho." },
  { 1, 0U, "Why Stumpy, I didn't know you were a dog's best friend." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 100U, "Time." },
  { 0, 50U, NULL },
  { 2, 100U, "Er." },
  { 0, 50U, NULL },
  { 3, 100U, "Slaught." },
  { 0, 50U, NULL },
  { 2, 100U, "Er." },
  { 0, 50U, NULL },
  { 1, 100U, "Time." },
  { 0, 50U, NULL },
  { 3, 100U, "Slaught." },
  { 1, 80U, "Time." },
  { 2, 80U, "Er." },
  { 3, 80U, "Slaught." },
  { 0, 100U, NULL },
  { 2, 80U, "Er." },
  { 1, 80U, "Time." },
  { 0, 100U, NULL },
  { 1, 80U, "Time." },
  { 3, 80U, "Slaught." },
  { 2, 80U, "Er." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 600U, "Who are you gonna vote for in the Presidential Election of 96\?" },
  { 2, 0U, "Presidential erection\?" },
  { 1, 0U, "I always bet on black." },
  { 3, 0U, "Hey, I'm running for president in '96." },
  { 3, 0U, "Midget brutality will end when I'm in office." },
  { 3, 0U, "I'm going to replace all the drunk congressmen with more capable drunk midgets." },
  { 3, 0U, "One nation under Stumpy, with foldable stools and ministilts for all!" },
  { 0, 300U, NULL },
  { -1, 0U, NULL },
  { 2, 600U, "Hey man, what's up with you and Luger\?" },
  { 1, 0U, "Lemme tell ya something brother..." },
  { 1, 0U, "..don't be talking that way unless you want a boot sandwich." },
  { 2, 0U, "Oh no! Not that!" },
  { 1, 0U,
    "...and after you've had your sandwich, I'm going to give you leg drop soup for "
    "dessert." },
  { 3, 0U, "It's a total debauchle!" },
  { 0, 300U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "Man, these electric chairs are nice and comfy." },
  { 1, 0U, "You know ALL about easy chairs." },
  { 2, 0U, "I know ALL about easy chairs." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Okay, explain this to me." },
  { 1, 0U, "You've got your four basic powers...." },
  { 1, 0U, "..you've got your fire, you got your water..." },
  { 1, 0U, "..there's earth and then you've got your wind." },
  { 1, 0U, "Now. Could some one please explain to me what heart does\?" },
  { 1, 0U, "Each of 'em has all these cool powers of the elements..." },
  { 1, 0U, "and then there's a little turd with a 'heart' ring!\?" },
  { 1, 0U, "What the HELL does heart do\? It's worthless!" },
  { 2, 0U, "Man, you know nothing of the Planeteers, do you\?" },
  { 2, 0U, "You need all 5 rings to summon Captain Planet..." },
  { 2, 0U, "It's common knowledge." },
  { 1, 0U, "I still think heart is useless." },
  { 3, 0U, "'Looting and polluting is the thing to do...'" },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Bulldozers are cool. " },
  { 2, 0U, "Yeah." },
  { 1, 0U, "Hard Hat Harry(TM) is a living god." },
  { 2, 0U, "Yeah." },
  { 1, 0U, "I could spend all day watching cows." },
  { 2, 0U, "Yeah." },
  { 1, 0U, "Those monotremes really know how to keep you coming back for more." },
  { 2, 0U, "They sure are a work of evolutionary genius." },
  { 2, 0U, "Two holes for the price of one!" },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Jihad! " },
  { 1, 0U, "Jihad! Jihad! JIHAD!!" },
  { 2, 0U, "You can't wage a Jihad." },
  { 1, 0U, "Why not\?" },
  { 2, 0U, "Because you aren't wearing your hawaiian shirt." },
  { 1, 0U, "I will be pinging the pong." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "brdbrbdbrbbdrbrbdbrbrd.....UGH! " },
  { 2, 0U, "Good Shadow impersonation." },
  { 1, 0U, "I like Carlos." },
  { 2, 0U, "You mean Erica\?" },
  { 1, 0U, "What are you talking about\? They look nothing alike, Carlos is a man." },
  { 2, 0U, "Maybe so..." },
  { 1, 0U, "My favorite Erica Storm quote is..." },
  { 1, 0U, "'You're just like all the street trash I wasted before!'" },
  { 2, 0U, "Erica didn't say that, Carlos did." },
  { 2, 0U, "'Is that all you got\?'" },
  { 2, 0U, "'Is that ALL you got\?'" },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 3, 0U, "Now you two alcohol swilling swine will fall before me." },
  { 2, 0U, "I like drinking beer out of the tall cans." },
  { 3, 0U, "Don't mock me." },
  { 1, 0U, "I dunno, the long neck bottles are pretty good." },
  { 3, 0U, "Shut up." },
  { 2, 0U, "Now that Australian beer, that is in really large cans." },
  { 3, 0U, "Nevermind..." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Hey look! It's a squeeky board on the floor." },
  { 1, 0U, "...I think I'll fondle it with my foot." },
  { 2, 0U, "And look! There are midget footprints all over the ceiling!." },
  { 1, 0U, "Something's smells midgety about all this..." },
  { 2, 0U, "Wait! I've got the mystery solved!" },
  { 2, 0U,
    "Stumpy used to be a carnival acrobat, and he doesn't need suction cups to climb on "
    "ceilings!" },
  { 2, 0U, "He must have done it!" },
  { 3, 0U, "You're right." },
  { 3, 0U,
    "And I would have gotten away with it if it weren't for you meddling perverts and that "
    "horny dog." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "dum dum dum dum...dum dum...STRODE!" },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Wouldn't that suck if someone took a dump on your car window\? " },
  { 2, 0U, "With me in it\? I would kick his ass." },
  { 1, 0U, "No, its a really big guy and you are strapped in." },
  { 2, 0U, "I'd drive away." },
  { 1, 0U, "No, what if the car won't start\?" },
  { 2, 0U, "That would suck." },
  { 1, 0U, "He squats and craps ever so slowly on your windshield as you sit there helpless." },
  { 2, 0U, "Stop it!" },
  { 1, 0U,
    "You struggle to block the flow by turning on your wipers, but alas, they are no match." },
  { 2, 0U, "Mommmmmmmmmmy!" },
  { 1, 0U, "Yeah, that's what I thought." },
  { 3, 0U, "How can you people be so damned jovial while I am electrocuting you\?" },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "Wow, someone's still playing our game." },
  { 1, 0U, "Stumpy, did you strap them in too\?" },
  { 3, 0U, "Nope, not me..." },
  { 1, 0U, "Maybe they actually like this game." },
  { 2, 0U, "No way, they must not have a life." },
  { 1, 0U,
    "They should be playing TIMESLAUGHTER, the one on one fighting beauty by Bloodlust "
    "Software." },
  { 2, 0U, "Due out summer 1993!" },
  { 1, 0U, "But wait, it's 1996." },
  { 2, 0U, "I guess the release date got moved back a tad." },
  { 1, 0U, "You call three years a tad\?" },
  { 2, 0U, "ok, maybe more like a smidgeon then." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "Hey person playing....go to our homepage!" },
  { 1, 0U, "Yeah, you can get all kinds of sick pictures, anti-morality propaganda, and games." },
  { 3, 0U, "Stay away from this page...they only want to make you hate midgets!" },
  { 1, 0U, "Do a net search for Bloodlust or midget, you'll find it!" },
  { 2, 0U, "I heard that page is really tasteless." },
  { 1, 0U, "Yeah, I love it." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Hey buddy, stop calling me buddy!" },
  { 2, 0U, "Sorry, bad habit. I'll try to stop, Ramona." },
  { 1, 0U, "Hey, my name's not Ramona..." },
  { 2, 0U, "Sorry about that, Ramona." },
  { 0, 200U, NULL },
  { 2, 0U, "Ramona...would you be a dear and pass me some of those crumpets\?" },
  { 1, 0U, "Call me Ramona again and I'll be forced to bludgeon you." },
  { 0, 200U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Ever wanted to know what the inside of a leg looked like\?" },
  { 2, 0U, "NOW you know!" },
  { 2, 0U, "I like the part where they blowtorch the live pigs..." },
  { 1, 0U, "Have you seen Faces of Death 3\? " },
  { 2, 0U, "Not only have I seen Faces of Death part 3..." },
  { 2, 200U, "I've seen Traces of Death 1, 2, and 3..." },
  { 2, 200U, "...I've seen Shadows of Death 1 and 2..." },
  { 2, 200U, "...umm, also Death Emporium, Smorgasboard of Death, Museum of Death..." },
  { 2, 200U, "I saw the collector's edition of Dead Death..." },
  { 2, 0U, "..and also Pot of Death." },
  { 0, 100U, NULL },
  { 1, 0U, "Death Pot comes from the sky." },
  { 2, 0U, "It does!" },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "Hey, did you remember to pay your cable bill\?" },
  { 1, 0U, "Ummm......" },
  { 2, 0U, "You better pay it or else Sergeant Toochie will be after you." },
  { 1, 0U, "I think I'll just bribe him, that's the way the system works for Toochie." },
  { 2, 0U, "We also better hide the stash of white slave girls in our basement." },
  { 1, 0U, "Yes! We must! I'll get Ralphus right on it..." },
  { 2, 0U, "She will dance, oh yes she will dance!" },
  { 1, 0U, "She will dance for our show!" },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Hey, if you had a daughter, what would you name her\?" },
  { 2, 0U, "I think that I'd name her 'Rimmer'." },
  { 1, 0U, "Oh yeah\?" },
  { 2, 0U, "Yeah, that way, if she has to escape from a space station..." },
  { 2, 0U, "...someone might say to her: " },
  { 2, 0U, "'It's time to pull out, Rimmer.'" },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 3, 0U, "After we get done in here...you guys are REALLY going to suffer!" },
  { 1, 0U, "I'm really scared." },
  { 3, 0U, "I'm going to take you two into the room of eternal pain and torture." },
  { 2, 0U, "Oh, is that the one room with the reruns of The Grind playing\?" },
  { 3, 0U, "Yeah, how'd you know\?" },
  { 2, 0U, "Just a wild guess." },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 1, 0U,
    "That would suck to be chased by the lord of hell, if he happened to arrive on Earth "
    "one day." },
  { 2, 0U, "Well, not really..." },
  { 2, 0U, "..you just gotta know how to deal with them there demons..." },
  { 1, 0U, "Oh yeah\?" },
  { 2, 0U, "Yeah!" },
  { 2, 0U, "If he forces you to walk down a hallway..." },
  { 2, 0U, "..all you gotta do is run through a door and shut it behind you!" },
  { 2, 0U, "He'll never be expecting it." },
  { 2, 0U, "Those lords of pain don't know how to operate modern doorknobs." },
  { 1, 0U, "Boy, you sure know a lot about battling demons and stuff." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "We don't need no retardation...." },
  { 2, 0U, "We don't need no limb control." },
  { 3, 0U, "Teacher! Leave those tards alone!" },
  { 1, 0U, "All in all, its just another tard drooling on the wall." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "When I get rich and famous, I'm going to hire a maid." },
  { 1, 0U, "Oh yeah\? Why is that\?" },
  { 2, 0U, "That way, when she cleans my bathroom she might touch my pee pee." },
  { 1, 0U, "I can see how that would be nice." },
  { 2, 0U, "And..you know, if I'm lucky she may touch my poo poo also." },
  { 1, 0U, "Such dreams and aspirations you have...." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 3, 0U, "You look like someone who would like some all-you-can-eat chili..." },
  { 1, 0U, "No thanks." },
  { 3, 0U, "You look like a growing chili boy!" },
  { 1, 0U, "No really, I'm stuffed." },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 3, 0U, "Hey, you guys look really familiar...." },
  { 1, 0U, "We do\?" },
  { 3, 0U, "Yeah." },
  { 3, 0U, "Weren't you the guys that made Executioners\?\?" },
  { 2, 0U, "Executioners\? Ummm...errr.... uhhhhh..." },
  { 1, 0U, "Well, gee...uhhh, well..hmmmm..." },
  { 2, 0U,
    "You mean that one side-scrolling fighting game with huge characters, tons of "
    "personality, and midget-chucking action\?" },
  { 3, 0U, "Yeah!! That's it! 'Executioners'..." },
  { 2, 0U, "Nope, never heard of it." },
  { 1, 0U, "Executioners\? Nope, draws a blank..." },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Hey, I wonder if we'll still be strapped to electric chairs in Noggin Knockers 3\?" },
  { 2, 0U, "I doubt it." },
  { 1, 0U,
    "Maybe in Noggin Knockers 3 we could actually spend more than a week making the game..." },
  { 1, 0U, "...and we could put in complex torture devices!" },
  { 2, 0U, "Complex torture devices\? Like what\?" },
  { 1, 0U,
    "Well, we could have a sharp drill that bores deeper into our heads each time we "
    "miss..." },
  { 2, 0U, "Ouch! That would hurt!" },
  { 1, 0U,
    "We could have a fat urine-smelling woman with one nipple dance erotically for the "
    "loser." },
  { 2, 0U, "We could hire Zoe real cheap." },
  { 1, 0U, "We could have a Craig Mack CD blasting in the ears of the loser...." },
  { 2, 0U, "That would be sheer torture!" },
  { 2, 0U, "I'd be on my knees, burning begging, baby please!" },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 1, 0U,
    "Have you ever looked up at the stars and wondered about the vastness of the universe\?" },
  { 2, 0U, "Yeah, actually I have..." },
  { 1, 0U, "When you realize how big everything is, it just really makes you feel small." },
  { 3, 0U, "Shut-up." },
  { 2, 0U, "Yeah, I look up at the things above me and I feel so darn tiny." },
  { 3, 0U, "Shut-up!" },
  { 1, 0U,
    "You don't know how much I'd like to put on super-tall ministilts so that I could "
    "touch the stars." },
  { 2, 0U, "Yeah, all those billionszz and billionsz of starsszh." },
  { 2, 0U, "You know, when a star blows up it gets turned into a white dwarf\?" },
  { 1, 0U,
    "Man, I sure feel sorry for that star. I bet all the tall stars pick on the white "
    "dwarfs." },
  { 3, 0U, "Enough of the midget puns already!" },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "Tirebiter! Tirebiter! Tirebiter!" },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "The itching...the itching and the burning...itching!!" },
  { 2, 0U, "The male itch...the itching..scratching....red rash... itch!" },
  { 1, 0U, "Uh oh, not this again..." },
  { 2, 0U, "...the burning! ...the itching! ...red, puffy rash! Winter itch!" },
  { 1, 0U, "Calm down! I think you're having a GoldBond (TM) flashback again!" },
  { 2, 0U, "Ahhhhh...that GoldBond (TM) powder helped to relieve my male itch." },
  { 0, 400U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "You know, I don't think this game is very astonishing." },
  { 2, 0U, "Why not\? It has humor, perversion, anti morality..." },
  { 1, 0U, "It doesn't have computer rendered graphics or digitized characters." },
  { 3, 0U, "Yes, you guys think art means you actually have to draw stuff." },
  { 2, 0U, "So you think if I threw on some pajamas and filmed myself it would be better." },
  { 3, 0U, "I would buy it...you know all artists are going to be replaced by computers." },
  { 1, 0U, "Then they will be astonishing, we don't need any artistic style to succeed." },
  { 2, 0U, "Yeah, polygons and live video are the new wave, I guess I'd better quit." },
  { 2, 0U, "Maybe I can get a job posing as a karate guy for a new three dimensional game." },
  { 1, 0U, "No, you have to be a scrawny little computer geek for that." },
  { 3, 0U, "I think you should call this game Ultimate Noggin Kombat Alpha Warriors Jet." },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "I'm going to kill the president..." },
  { 2, 0U, "...of the Hair Club for Men." },
  { 1, 0U, "Don't even joke like that." },
  { 1, 0U, "You can be arrested for threatening the life of the president." },
  { 2, 0U, "That's ridiculous, what about our first ammendment\?" },
  { 1, 0U, "You should know by now the government makes the laws, they don't follow them." },
  { 2, 0U, "Oh yeah, I guess you are right." },
  { 1, 0U, "Welcome to democracy." },
  { 2, 0U, "I'm going to get him in the dining room with the lead pipe." },
  { 1, 0U, "hehe." },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "I don't wanna grow up, I'm a beanbag kid!" },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Hey stop with that self stimulating behavior!" },
  { 2, 0U, "No." },
  { 1, 0U, "What if I give you a lollipop\?" },
  { 2, 0U, "Ok." },
  { 1, 0U, "There, that's better, I'm so gla...HEY! I told you to stop!" },
  { 2, 0U, "This way I get to have fun AND I get free lollipops, why would I stop\?" },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Hey the person playing could be a game reviewer!" },
  { 2, 0U, "Uh Oh." },
  { 1, 0U, "Really, game reviewer person, this isn't the extent of our skills." },
  { 2, 0U, "Yes, we just made this between good games for fun." },
  { 1, 0U, "I know! I'll bribe the game reviewer!" },
  { 2, 0U, "Yes, use your programming skills to transfer 500 dollars to their bank account." },
  { 1, 0U, "Ok, transferring funds..." },
  { 2, 0U, "There, now we get a good game review through true American methods." },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Oooooh look at you in all black, what are you into the goth scene\?" },
  { 2, 0U, "Just because I wear fake vampire teeth and black lipstick doesn't mean I am Goth." },
  { 1, 0U, "What about your candle collection and the way you drink blood\?" },
  { 2, 0U, "Chicks dig guys who drink blood." },
  { 1, 0U, "Really, I always chew on their intestines, maybe that's what I'm doing wrong." },
  { 2, 0U, "See, you can learn a lot from a Got...er, guy who wears black." },
  { 3, 0U, "You two are disgusting, we midgets know exactly what pleases a woman." },
  { 2, 0U, "Too bad you can't reach it." },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "infooooma" },
  { 2, 0U, "yaknow saydaddymesnow meuptoblame." },
  { 3, 0U, "policemansay medaddymestump meshotsomeonedown thelaaane" },
  { 2, 0U, "alickey boom boom down." },
  { 1, 0U, "Rap sucks." },
  { 2, 0U, "I wish there was an alternative to rap." },
  { 3, 0U, "There is, it's called Alternative." },
  { 2, 0U, "I wish there was an Alternative to Alternative." },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 1, 0U, "Man that clapper trap was mean, you really fell for it." },
  { 2, 0U, "At least I didn't get eaten by a cow that you could plainly see Stumpy riding." },
  { 1, 0U, "How did you know that\?" },
  { 2, 0U, "Easy, I watched the credits cinematic at the beginning of the game." },
  { 1, 0U, "We are in a computer game\?" },
  { 2, 0U, "Yes, Stumpy must have trapped us here." },
  { 3, 0U, "Shhhhhh...you are going to spoil the elaborate trap I have set for the player." },
  { 2, 0U, "Run player!!!!! Run while you still can!!!!!" },
  { 0, 600U, NULL },
  { -1, 0U, NULL },
  { 2, 0U, "Hey, the person playing just won..." },
  { 2, 0U, "I bet the girls are all falling at his or her feet right now." },
  { 1, 0U, "I doubt it. All the girls are falling at Buddy's feet...he's such a stud." },
  { 2, 0U,
    "You twit! The reason girls keep falling at Buddy's feet is because they keep slipping "
    "on his drool." },
  { 1, 0U, "Buddy is a pimp!" },
  { 1, 0U, "Buddy is the mack daddy." },
  { 2, 0U, "You know why Buddy never gets a girl pregnant\?" },
  { 1, 0U, "Does he use protection\?" },
  { 2, 0U, "No, it's because he has an extra chromosome." },
  { 1, 0U, "XXY!" },
  { 2, 0U, "XXY!" },
  { 0, 2000U, NULL },
  { 1, 0U, "Press the damn button already!" },
  { 2, 0U, "Hurry your ass up, we're getting bored." },
  { -1, 0U, NULL },
  { 2, 0U, "Hey, the person playing just won..." },
  { 2, 0U, "That means they receive the grand prize!" },
  { 1, 0U, "Yes." },
  { 1, 0U, "Ummm...I didn't know we gave away prizes\?" },
  { 2, 0U, "Well, we were going to give away a free skin illustration to every winner." },
  { 1, 0U, "Skin illustration\? You mean a tattoo\?" },
  { 2, 0U, "They are not tattoos! They are skin illustrations!!" },
  { 1, 0U, "Hey hey...chill out. Tattoo illustrations are cool.." },
  { 2, 0U, "They are NOT TATTOOS! THEY ARE SKIN ILLUSTRATIONS!!" },
  { 1, 0U, "Oh." },
  { 0, 2000U, NULL },
  { 1, 0U, "Press the damn button already!" },
  { 2, 0U, "Hurry your ass up, we're getting bored." },
  { -1, 0U, NULL },
  { 2, 0U, "Wow...we have a winner." },
  { 2, 0U, "You must not have programmed the computer very well." },
  { 1, 0U, "No it's like chess you see, I let them win this time." },
  { 1, 0U, "That way I build up false psychological hope and crush it later." },
  { 2, 0U, "So you are saying the player is a mere pawn in the big picture\?" },
  { 1, 0U, "Yes, I am dominating the player's life, crafting it to my very whims." },
  { 2, 0U, "And soon you can make the player do anything you want\?" },
  { 1, 0U, "Yes, you see how the pieces are falling into place." },
  { 2, 0U, "What if they just turn the game off\?" },
  { 1, 0U, "Shhhhhhhhhh!" },
  { 0, 2000U, NULL },
  { 1, 0U, "Press the damn button already!" },
  { 2, 0U, "Hurry your ass up, we're getting bored." },
  { -1, 0U, NULL },
  { 2, 0U, "Wow, the player is on a roll." },
  { 2, 0U, "Maybe the player is a cool person after all!" },
  { 1, 0U, "No way, think about what they are doing." },
  { 1, 0U, "They are actually skilled at a crappy little pong game that we threw together." },
  { 2, 0U, "True, they could spend their time better Milking Buffalo." },
  { 1, 0U, "...or sending bombs in the mail to political officials." },
  { 2, 0U, "...or having romance on internet chat programs with ugly chicks." },
  { 1, 0U, "...or coveting thy neighboor's sheep." },
  { 2, 0U, "...or making blue toilet water green." },
  { 1, 0U, "...or waiting 20 seconds to see the really cool thing we'll say next." },
  { 0, 2000U, NULL },
  { 1, 0U, "Press the damn button already!" },
  { 2, 0U, "Hurry your ass up, we're getting bored." },
  { -1, 0U, NULL },
  { 2, 0U, "Hey, the person playing just lost..." },
  { 1, 0U, "What a loser." },
  { 2, 0U, "Go cry to momma!" },
  { 1, 0U, "Momma's little baby. Waaaa waaaa." },
  { 2, 0U, "Just end your misery and put a gun to your head..." },
  { 1, 0U, "We have a problem in today's society with teenagers blowing their own brains out." },
  { 1, 0U, "Such a waste..." },
  { 2, 0U, "...a waste of a bullet." },
  { 1, 0U, "Yeah, why can't they just slit their wrists like we did back in the old days\?" },
  { 2, 0U, "You can reuse knifes over and over. Recycling is the future." },
  { 0, 2000U, NULL },
  { 1, 0U, "Press the damn button already!" },
  { 2, 0U, "Hurry your ass up, we're getting bored." },
  { -1, 0U, NULL },
  { 2, 0U, "What, you lost again\?" },
  { 1, 0U, "Do you have limb control problems or something\?" },
  { 2, 0U, "Maybe the person playing is having an epileptic fit." },
  { 1, 0U, "The flashy lights can do that to you." },
  { 0, 2000U, NULL },
  { 1, 0U, "Press the damn button already!" },
  { 2, 0U, "Hurry your ass up, we're getting bored." },
  { -1, 0U, NULL },
  { 2, 0U, "If you keep losing like that, you'll never see the spiffy endings." },
  { 1, 0U, "Endings\? There are endings in this game\?" },
  { 2, 0U, "Yeah you tosser, we made this game remember\? You should know!" },
  { 1, 0U, "I didn't know this game even ended, I thought we were trapped here forever." },
  { 0, 2000U, NULL },
  { 1, 0U, "Press the damn button already!" },
  { 2, 0U, "Hurry your ass up, we're getting bored." },
  { -1, 0U, NULL },
  { 2, 0U, "Tsk tsk tsk..." },
  { 1, 0U, "You naughty boy you." },
  { 2, 0U, "You're supposed to hit the head back each time...didn't you read the instructions\?" },
  { 1, 0U,
    "Yeah, we spent a whole 5 minutes writing the instructions and you still miss the head." },
  { 0, 2000U, NULL },
  { 1, 0U, "Press the damn button already!" },
  { 2, 0U, "Hurry your ass up, we're getting bored." },
  { -1, 0U, NULL },
  { 2, 0U, "Have faith, we know that winning this game is one of your ambitions." },
  { 1, 0U, "Yes, don't let herpes get in the way of your dreams..." },
  { 2, 0U, "Herpes thrives on ignorance." },
  { -1, 0U, NULL },
  { 2, 0U, "Well, finally." },
  { 1, 0U, "Yeah, we've been waiting forever." },
  { 1, 0U, "My ass feels like it's asleep." },
  { 1, 0U, "You beat all the characters." },
  { 2, 0U, "Yes, you have beaten them all..." },
  { 1, 0U, "You've knocked the noggin quite successfully." },
  { 2, 0U, "Now is the time where you get to see the ending." },
  { 1, 0U, "Yeah, so, let's fire that ending up..." },
  { 1, 0U, "Okay, any moment now..." },
  { 1, 0U, "Hey wait, you need to press the button first." },
  { 2, 0U, "Yeah, press the damn button so we can get the hell outta here." },
  { -1, 0U, NULL },
  { 0, 100U, NULL },
  { 0, 100U, NULL },
  { -1, 0U, NULL },
};

const NkDialogueConversation nk_dialogue_ambient[] =
{
  { 0U, 12U }, /* intro */
  { 12U, 10U }, /* shutup */
  { 22U, 17U }, /* squat */
  { 39U, 14U }, /* notliketard */
  { 53U, 6U }, /* tirebiter */
  { 59U, 5U }, /* nipple */
  { 64U, 12U }, /* piss */
  { 76U, 11U }, /* bulge */
  { 87U, 15U }, /* underwear */
  { 102U, 11U }, /* cavity */
  { 113U, 23U }, /* bud */
  { 136U, 9U }, /* president */
  { 145U, 8U }, /* luger */
  { 153U, 5U }, /* easychair */
  { 158U, 15U }, /* captainplanet */
  { 173U, 11U }, /* bulldozers */
  { 184U, 8U }, /* jihad */
  { 192U, 13U }, /* shadow */
  { 205U, 9U }, /* beer */
  { 214U, 11U }, /* scooby */
  { 225U, 3U }, /* strode */
  { 228U, 14U }, /* car */
  { 242U, 13U }, /* wow */
  { 255U, 8U }, /* homepage */
  { 263U, 9U }, /* buddy */
  { 272U, 15U }, /* facesofdeath */
  { 287U, 10U }, /* cable */
  { 297U, 8U }, /* rimmer */
  { 305U, 8U }, /* grind */
  { 313U, 12U }, /* demon */
  { 325U, 6U }, /* retardation */
  { 331U, 8U }, /* peepee */
  { 339U, 6U }, /* chili */
  { 345U, 12U }, /* executioners */
  { 357U, 14U }, /* nn3 */
  { 371U, 13U }, /* stars */
  { 384U, 3U }, /* tb */
  { 387U, 8U }, /* goldbond */
  { 395U, 13U }, /* astonish */
  { 408U, 12U }, /* hairpresident */
  { 420U, 3U }, /* beanbag */
  { 423U, 8U }, /* lolli */
  { 431U, 10U }, /* Review */
  { 441U, 10U }, /* goth */
  { 451U, 10U }, /* snow */
  { 461U, 10U }, /* trap */
};

const NkDialogueConversation nk_dialogue_win[] =
{
  { 471U, 15U }, /* win1 */
  { 486U, 14U }, /* win2 */
  { 500U, 14U }, /* win3 */
  { 514U, 14U }, /* win4 */
};

const NkDialogueConversation nk_dialogue_loss[] =
{
  { 528U, 14U }, /* lost */
  { 542U, 8U }, /* lost2 */
  { 550U, 8U }, /* lost3 */
  { 558U, 8U }, /* lost4 */
  { 566U, 4U }, /* lost5 */
};

const NkDialogueConversation nk_dialogue_ending[] =
{
  { 570U, 12U }, /* endingtext */
};

const NkDialogueConversation nk_dialogue_post_match[] =
{
  { 582U, 3U }, /* donetext */
};

const u16 nk_dialogue_entry_count = 585U;
